# This is for linting. To run it, please use:
# golangci-lint run ${MODULE}/... [--fix]

version: "2"
linters:
  # linters to run in addition to default ones
  enable:
    - copyloopvar
    - dupl
    - durationcheck
    - errname
    - errorlint
    - forbidigo
    - forcetypeassert
    - godot
    - gosec
    - misspell
    - revive
    - thelper
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - whitespace
  settings:
    # Forbid the usage of deprecated ioutil and debug prints
    forbidigo:
      forbid:
        - pattern: ioutil\.
        - pattern: ^print.*$
    # Ensure that we always explain why we are ignoring a linter and which one is being ignored.
    nolintlint:
      require-explanation: true
      require-specific: true
  exclusions:
    generated: lax
    rules:
      # EXC0001 errcheck: most errors are in defer calls, which are safe to ignore and idiomatic Go (would be good to only ignore defer ones though)
      - path: (.+)\.go$
        text: Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*print(f|ln)?|os\.(Un)?Setenv|w\.Stop). is not checked
      # EXC0008 gosec: duplicated of errcheck
      - path: (.+)\.go$
        text: (G104|G307)
      # EXC0010 gosec: False positive is triggered by 'src, err := ioutil.ReadFile(filename)'
      - path: (.+)\.go$
        text: Potential file inclusion via variable
      # revive: unexported-return for functions exported only in tests, aliasing doesn't work here as the linter always goes for the underlying model which is unexported
      - path: (.+)\.go$
        text: 'unexported-return: exported func InitialModel(ForTests|WithPrevConfig)? returns unexported type watchdtui.model, which can be annoying to use'
      # Sometimes it is more readable to do a `if err := a(); err != nil` than simply `return a()`
      - path: (.+)\.go$
        text: if-return
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
