name: Check if CLA is signed
on:
  pull_request_target:

jobs:
  cla-check:
    name: Check if CLA is signed
    runs-on: ${{ vars.RUNNER }}
    steps:
      - name: Check if CLA signed
        uses: canonical/has-signed-canonical-cla@v2
        with:
          accept-existing-contributors: true
